    Calculate geomagnetic field at a given location and obstime. 'IGRF13' geomagnetic model is used as default. 

    Using the 'geomagnetic' module, the magnetic field can be defined in two different ways (see below) depending on the input location. The default geomagnetic model ('IGRF13') and default obstime ('2020-01-01') are used if not given.
    
        Geomagnet(model: str= 'IGRF13',
                  latitude : Union[Number, np.ndarray] = None,
                  longitude: Union[Number, np.ndarray] = None,
                  height   : Union[Number, np.ndarray] = None,
                  location : Union[ECEF, Geodetic, GRANDCS]=None,
                  obstime  : Union[str, datetime.date] = '2020-01-01') -> CartesianRepresentation:

        
        1. Location can be given as ECEF, Geodetic, LTP, or GRAND coordinate system. 'x' below can be in ECEF, Geodetic, LTP, or GRANDCS.
        
            gm = Geomagnet(location=x)    
            gm = Geomagnet(location=x, model='IGRF13', obstime='2021-08-30')
            
        2. Location can be given as latitude, longitude, and height.
        
            gm = Geomagnet(latitude=0, longitude=0, height=0)
            gm = Geomagnet(latitude=0, longitude=0, height=0, model='IGRF13', obstime='2020-08-30')
            
    TypeError will occur if location is not provided. For observation time (obstime), provide time in isoformat ('2020-08-30') or in datetime.date(2020, 8, 30). If obstime is not provided, a default date ('2020-01-01') is used. After the geomagnetic field is instantiated, you can get the required quantity by:
    
        field       = gm.field          Output: CartesianRepresentation(x=Bx, y=By, z=Bz)
        declination = gm.declination    Output: in degree
        inclination = gm.inclination    Output: in degree
        model       = gm.model          Output: in string
        obstime     = gm.obstime        Output: in datetime.date()
        location    = gm.location       Output: in Geodetic(latitude=x, longitude=x, height=x)
    

In [1]:
from grand import Geomagnet, Geodetic

import numpy as np
import datetime

Welcome to JupyROOT 6.26/02


In [2]:
print("---------Geomagnetic Field--------")

# Define a location. More on this later. Location of equator and GRANDCS origin (approx.) is used.
loc1 = Geodetic(latitude=0, longitude=0, height=1)
loc2 = Geodetic(latitude=38.87253, longitude=92.35731, height=2797.026)  # possible GRANDCS origin.

# instantiate a global geomagnetic field based on a model, location and observation time.
# Model and observation time has default values ('IGRF13', datetime.date(2020, 1, 1)).
# Location must be provided. It can be given in ECEF, Geodetic, or GRAND coordinate system.
# Or location can be given as latitude (deg), longitude (deg), and height (m) asl.
# Observation time should be given in isoformat or in datetime.date().

geoB1 = Geomagnet(location=loc1)  # default model and obstime is used.

geoB2 = Geomagnet(latitude=0, longitude=0, height=1)  # default model and obstime is used.

geoB3 = Geomagnet(model="IGRF13", location=loc2, obstime="2021-08-30")
# or geoB3 = Geomagnet(location=loc2, obstime=datetime.date(2021, 8, 30))

geoB4 = Geomagnet(model="WMM2020", location=loc2, obstime="2021-08-30")

print("")
print("-- Magneitc Field (B)")
print(geoB1.field, type(geoB1.field))
print("-- Observation time")
print(geoB1.obstime, type(geoB1.obstime))
print("-- Location")
print(geoB1.location, type(geoB1.location))
print("--")
print(
    "Declination [deg]:",
    round(geoB1.declination, 3),
    ",  Inclination [deg]:",
    round(geoB1.inclination, 3),
)
print("....................\n")

print("-- Magneitc Field (B)")
print(geoB2.field, type(geoB2.field))
print("-- Observation time")
print(geoB2.obstime, type(geoB2.obstime))
print("-- Location")
print(geoB2.location, type(geoB2.location))
print("--")
print(
    "Declination [deg]:",
    round(geoB2.declination, 3),
    ",  Inclination [deg]:",
    round(geoB2.inclination, 3),
)
print("....................\n")

print("-- Magneitc Field (B) at GRANDCS Origin")
print(geoB3.field, type(geoB3.field))
print("-- Observation time")
print(geoB3.obstime, type(geoB3.obstime))
print("-- Location")
print(geoB3.location, type(geoB3.location))
print("-- ")
print(
    "Declination [deg]:",
    round(geoB3.declination, 5),
    ",  Inclination [deg]:",
    round(geoB3.inclination, 5),
)
print("....................\n")

print("-- Magneitc Field (B) at GRANDCS Origin. magnetic model: WMM2020")
print(geoB4.field, type(geoB4.field))
print("-- Observation time")
print(geoB4.obstime, type(geoB4.obstime))
print("-- Location")
print(geoB4.location, type(geoB4.location))
print("-- ")
print(
    "Declination [deg]:",
    round(geoB4.declination, 5),
    ",  Inclination [deg]:",
    round(geoB4.inclination, 5),
)
print("....................\n")

---------Geomagnetic Field--------

-- Magneitc Field (B)
[[-2.24188795e-06]
 [ 2.75399734e-05]
 [ 1.60124534e-05]] <class 'grand.geo.coordinates.CartesianRepresentation'>
-- Observation time
2020-01-01 <class 'datetime.date'>
-- Location
[[0.]
 [0.]
 [1.]] <class 'grand.geo.coordinates.Geodetic'>
--
Declination [deg]: -4.654 ,  Inclination [deg]: -30.093
....................

-- Magneitc Field (B)
[[-2.24188795e-06]
 [ 2.75399734e-05]
 [ 1.60124534e-05]] <class 'grand.geo.coordinates.CartesianRepresentation'>
-- Observation time
2020-01-01 <class 'datetime.date'>
-- Location
[[0.]
 [0.]
 [1.]] <class 'grand.geo.coordinates.Geodetic'>
--
Declination [deg]: -4.654 ,  Inclination [deg]: -30.093
....................

-- Magneitc Field (B) at GRANDCS Origin
[[ 2.15525466e-07]
 [ 2.81105530e-05]
 [-4.77043114e-05]] <class 'grand.geo.coordinates.CartesianRepresentation'>
-- Observation time
2021-08-30 <class 'str'>
-- Location
[[  38.87253]
 [  92.35731]
 [2797.026  ]] <class 'grand.geo.coor